-- MySQL Script generated by MySQL Workbench
-- Tue Jun  8 20:22:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jarvis_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jarvis_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jarvis_db` DEFAULT CHARACTER SET utf8 ;
USE `jarvis_db` ;

-- -----------------------------------------------------
-- Table `jarvis_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `img_url` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_categoria_idx` (`categoria_idcategoria` ASC) ,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `jarvis_db`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`cartao` (
  `numero_cartao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cvv` INT NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`numero_cartao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`endereco` (
  `idendereco` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `cep` INT NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`cliente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `gastoTotal` FLOAT NOT NULL,
  `cartao_numero_cartao` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_cliente_cartao1_idx` (`cartao_numero_cartao` ASC) ,
  INDEX `fk_cliente_endereco1_idx` (`endereco_idendereco` ASC) ,
  CONSTRAINT `fk_cliente_cartao1`
    FOREIGN KEY (`cartao_numero_cartao`)
    REFERENCES `jarvis_db`.`cartao` (`numero_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `jarvis_db`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `precoTotal` VARCHAR(45) NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  INDEX `fk_carrinho_produto1_idx` (`produto_idproduto` ASC) ,
  CONSTRAINT `fk_carrinho_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `jarvis_db`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`status` (
  `idstatus` INT NOT NULL,
  `nome_status` VARCHAR(45) NOT NULL,
  `tempo_preparacao` VARCHAR(45) NULL,
  `tempo_embalagem` VARCHAR(45) NULL,
  `tempo_entrega` VARCHAR(45) NULL,
  `tempo_finalizado` VARCHAR(45) NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`pedido` (
  `idpedido` INT NOT NULL,
  `data` DATE NOT NULL,
  `avaliacao` VARCHAR(45) NOT NULL,
  `cartao_numero_cartao` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  `carrinho_idcarrinho` INT NOT NULL,
  `status_idstatus` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cartao1_idx` (`cartao_numero_cartao` ASC) ,
  INDEX `fk_pedido_endereco1_idx` (`endereco_idendereco` ASC) ,
  INDEX `fk_pedido_carrinho1_idx` (`carrinho_idcarrinho` ASC) ,
  INDEX `fk_pedido_status1_idx` (`status_idstatus` ASC) ,
  CONSTRAINT `fk_pedido_cartao1`
    FOREIGN KEY (`cartao_numero_cartao`)
    REFERENCES `jarvis_db`.`cartao` (`numero_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `jarvis_db`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_carrinho1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `jarvis_db`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `jarvis_db`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`funcionario` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`preparacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`preparacao` (
  `idpreparacao` INT NOT NULL,
  `tempoMedioGasto` FLOAT NOT NULL,
  `pedido_idpedido` INT NULL,
  `funcionario_cpf` INT NOT NULL,
  PRIMARY KEY (`idpreparacao`),
  INDEX `fk_preparacao_pedido1_idx` (`pedido_idpedido` ASC) ,
  INDEX `fk_preparacao_funcionario1_idx` (`funcionario_cpf` ASC) ,
  CONSTRAINT `fk_preparacao_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `jarvis_db`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preparacao_funcionario1`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `jarvis_db`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`embalagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`embalagem` (
  `idembalagem` INT NOT NULL,
  `tempoMedioGasto` FLOAT NOT NULL,
  `pedido_idpedido` INT NULL,
  `funcionario_cpf` INT NOT NULL,
  PRIMARY KEY (`idembalagem`),
  INDEX `fk_embalagem_pedido1_idx` (`pedido_idpedido` ASC) ,
  INDEX `fk_embalagem_funcionario1_idx` (`funcionario_cpf` ASC) ,
  CONSTRAINT `fk_embalagem_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `jarvis_db`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embalagem_funcionario1`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `jarvis_db`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`entrega` (
  `identrega` INT NOT NULL,
  `tempoMedioGasto` FLOAT NOT NULL,
  `data_prevista` DATE NOT NULL,
  `pedido_idpedido` INT NULL,
  `funcionario_cpf` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  INDEX `fk_entrega_pedido1_idx` (`pedido_idpedido` ASC) ,
  INDEX `fk_entrega_funcionario1_idx` (`funcionario_cpf` ASC) ,
  CONSTRAINT `fk_entrega_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `jarvis_db`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_funcionario1`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `jarvis_db`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jarvis_db`.`dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jarvis_db`.`dashboard` (
  `iddashboard` INT NOT NULL,
  `tempoTotalEntrega` VARCHAR(45) NOT NULL,
  `cliente_cpf` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`iddashboard`),
  INDEX `fk_dashboard_cliente1_idx` (`cliente_cpf` ASC) ,
  INDEX `fk_dashboard_produto1_idx` (`produto_idproduto` ASC) ,
  INDEX `fk_dashboard_endereco1_idx` (`endereco_idendereco` ASC) ,
  CONSTRAINT `fk_dashboard_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `jarvis_db`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dashboard_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `jarvis_db`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dashboard_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `jarvis_db`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
